//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new person.
        /// </summary>
        public static string AddNewPersonButtonLabel {
            get {
                return ResourceManager.GetString("AddNewPersonButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string AgeHeaderDataGridLabel {
            get {
                return ResourceManager.GetString("AgeHeaderDataGridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Number.
        /// </summary>
        public static string ApartmentNumberHeaderDataGridLabel {
            get {
                return ResourceManager.GetString("ApartmentNumberHeaderDataGridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Birth.
        /// </summary>
        public static string BirthDateHeaderDataGridLabel {
            get {
                return ResourceManager.GetString("BirthDateHeaderDataGridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please waiting....
        /// </summary>
        public static string BusyLabel {
            get {
                return ResourceManager.GetString("BusyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find current user profile path.
        /// </summary>
        public static string CannotFindCurrentUserProfilePathExceptionMessage {
            get {
                return ResourceManager.GetString("CannotFindCurrentUserProfilePathExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please check application logs..
        /// </summary>
        public static string ErrorMessageBoxContentText {
            get {
                return ResourceManager.GetString("ErrorMessageBoxContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNameHeaderDataGridLabel {
            get {
                return ResourceManager.GetString("FirstNameHeaderDataGridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Number.
        /// </summary>
        public static string HouseNumberHeaderDataGridLabel {
            get {
                return ResourceManager.GetString("HouseNumberHeaderDataGridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNameHeaderDataGridLabel {
            get {
                return ResourceManager.GetString("LastNameHeaderDataGridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCS.
        /// </summary>
        public static string MainWindowTitleLabel {
            get {
                return ResourceManager.GetString("MainWindowTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cannot be empty.
        /// </summary>
        public static string NoDataErrorText {
            get {
                return ResourceManager.GetString("NoDataErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumberHeaderDataGridLabel {
            get {
                return ResourceManager.GetString("PhoneNumberHeaderDataGridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCodeHeaderDataGridLabel {
            get {
                return ResourceManager.GetString("PostalCodeHeaderDataGridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string StreetNameHeaderDataGridLabel {
            get {
                return ResourceManager.GetString("StreetNameHeaderDataGridLabel", resourceCulture);
            }
        }
    }
}
